config/routes.rb
Rails.application.routes.draw do
  get 'homes/show'

  root to: 'homes#show', via: :get
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resource :dashboard, only: [:show] #singleton resourse
  resources :shouts, only: [:create, :show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shout.rb
class Shout < ApplicationRecord
  belongs_to :user
  validates :body, presence: true

  default_scope { order("created_at DESC") }
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true
  has_many :shouts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  protect_from_forgery with: :exception
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show
    @shout = Shout.new
    @shouts = current_user.shouts
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :check_logged_in_user
  def show
  end

  private

  def check_logged_in_user
    if signed_in?
      redirect_to dashboard_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create], raise: false

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/shouts_controller.rb
class ShoutsController < ApplicationController

  def create
    shout = current_user.shouts.build(shout_params)
    if shout.save
      redirect_to dashboard_path, notice: "You shouted!"
    else
      redirect_to dashboard_path, alert: "Could not shout!"
    end
  end

  def show
    @shout = Shout.find(params[:id])
  end

  private

  def shout_params
    params.require(:shout).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create], raise: false

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)

    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @user = current_user
    @shouts = @user.shouts
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/shouts_helper.rb
module ShoutsHelper
end

app/views/dashboards/show.html.erb
<h2>My dashboard</h2>
<div class="row m-2">
  <%= form_for @shout do |f| %>
    <%= f.text_field :body, placeholder: 'Shout content here' %>
    <%= f.submit 'Shout' %>
  <% end %>
</div>

<div class="row">
  <%= render @shouts %>
</div>

app/views/homes/show.html.erb
<h1>Welcome to Shouter</h1>
<p>Find me in app/views/homes/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shouter</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="#">Workout App</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Home', root_path, class:"nav-link" %><span class="sr-only">(current)</span></a>
          </li>

          <% if signed_in? %>
            <span class="navbar-text">
              Signed in as <%= link_to current_user.username, dashboard_path %>
            </span>
            <li class="nav-item">
              <%= link_to 'Logout', session_path, method: :delete, class:"nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to 'Sign in', new_session_path, class:"nav-link" %>
            </li>
          <% end %>

        </ul>
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    <div class="container">
      <div class="row">
      <div class="col-md-12">
        <% flash.each do |key, msg| %>
          <div class="text-center alert alert-<%= key == 'notice' ? 'success' : 'danger' %>">
            <%= msg %>
        </div>
        <% end %>
      </div>
    </div>
      <%= yield %>
    </div>

  </body>
</html>

app/views/shouts/_shout.html.erb
<div class="col-3">
  <div class="card">
    <h2><%= link_to shout.user.username, shout.user %> <small>shouted</small></h2>
    <p><%= shout.body %> - <%= link_to time_ago_in_words(shout.created_at), shout%> ago</p>
  </div>
</div>

app/views/shouts/show.html.erb
<div class="row">
  <%= render @shout %>
</div>

app/views/users/new.html.erb
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :username %>
    <%= form.text_field :username, require: true %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email, require: true %>
  </div>


  <div>
    <%= form.label :password %>
    <%= form.password_field :password, require: true %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="row">
  <h1><%= @user.username %></h1>
</div>

<div class="row">
  <%= render @shouts %>
</div>